- name: "installing yum packages"
  apt:
    name:  
    - curl 
    - wget 
    - vim 
    - git
    - unzip
    - socat
    - bash-completion
    - php7.4
    - php7.4-cli
    - php7.4-fpm
    - php7.4-common
    - php7.4-xml
    - php7.4-gd
    - php7.4-zip
    - php7.4-mbstring
    - php7.4-mysql
    - php7.4-pgsql
    - php7.4-sqlite3
    - php7.4-opcache
    - php-apcu
    - nginx
    - mysql-server
    - php7.4-dev
    - python3-pip
    state: present
  
- name: "need mysql python module"
  pip:
    name: pymysql


